apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  redis-password: {{ .Values.redisSentinel.secret.redisPassword }} # Base64-encoded 'password' or use plain 'stringData' below
